### ISSUE TITLE
SyntaxError python 3.5

### ISSUE THREAD

**Issue by JohannesBuchner** [JohannesBuchner/imagehash#184]
CI is failing https://github.com/JohannesBuchner/imagehash/actions/runs/3973927549

```
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 18, in <module>
    import _pytest._code
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/_pytest/_code/__init__.py", line 3, in <module>
    from .code import Code  # noqa
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/_pytest/_code/code.py", line 8, in <module>
    import attr
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/attr/__init__.py", line 8, in <module>
    from . import converters, exceptions, filters, setters, validators
  File "/usr/share/miniconda/envs/test/lib/python3.5/site-packages/attr/converters.py", line 144
    raise ValueError(f"Cannot convert value to bool: {val}")
                                                          ^
SyntaxError: invalid syntax
Coverage.py warning: No data was collected. (no-data-collected)
Error: Process completed with exit code 1.
```

**Comment by JohannesBuchner** [comment]
Seems `attr` does not support python 3.5 anymore.
