### ISSUE TITLE
Can ImageHash be installed with Python 3.12?

### ISSUE THREAD

**Issue by luckman212** [JohannesBuchner/imagehash#194]
I tried to start up a new virtualenv project with Python 3.12 + ImageHash (installed with `pip`)

```
mkvirtualenv myproj --python=python3.12
pip install ImageHash
```

Got this error:
```
Collecting ImageHash
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting PyWavelets (from ImageHash)
  Using cached PyWavelets-1.4.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/luke/.virtualenvs/myproj/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/luke/.virtualenvs/myproj/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/luke/.virtualenvs/myproj/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/luke/.virtualenvs/myproj/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-6oak2mar/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-6oak2mar/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/n1/kwxhk1g96vl592mftk5lwntc0000gn/T/pip-build-env-6oak2mar/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Manually specifying Python 3.11 worked. Just wondering if anyone's seen this and knows of a workaround?

**Comment by JohannesBuchner** [comment]
Try the same, but without ImageHash and with  `pip install PyWavelets`. If the same error occurs, which I suspect, this is a bug for PyWavelets. If not, please reopen.

**Comment by luckman212** [comment]
Thanks @JohannesBuchner 

You are correct, the problem appears to be with PyWavelets! I'll try another route.

**Comment by luckman212** [comment]
In case someone else lands here, this seems like it will eventually point to something useful

[Create pip_install_on_py3_12.yml by cclauss · Pull Request #693 · PyWavelets/pywt](https://github.com/PyWavelets/pywt/pull/693)
