### ISSUE TITLE
Can not install on Ubuntu 

### ISSUE THREAD

**Issue by k0fi** [JohannesBuchner/imagehash#40]
I tried to install imagehash on Ubuntu 14.04 using a blank virtualenv running python 2.7 and pip.
First it complained that numpy not installed. After that I tried again and got this:

```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/pc/.testenv/build/scipy/setup.py", line 415, in <module>

    setup_package()

  File "/home/pc/.testenv/build/scipy/setup.py", line 411, in setup_package

    setup(**metadata)

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup

    config = configuration()

  File "/home/pc/.testenv/build/scipy/setup.py", line 335, in configuration

    config.add_subpackage('scipy')

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage

    caller_level = 2)

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage

    caller_level = caller_level + 1)

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy/setup.py", line 15, in configuration

    config.add_subpackage('linalg')

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage

    caller_level = 2)

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage

    caller_level = caller_level + 1)

  File "/home/pc/.testenv/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy/linalg/setup.py", line 20, in configuration

    raise NotFoundError('no lapack/blas resources found')

numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

----------------------------------------
Cleaning up...
Command /home/pc/.testenv/bin/python -c "import setuptools, tokenize;__file__='/home/pc/.testenv/build/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-AQ6kBT-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pc/.testenv/include/site/python2.7 failed with error code 1 in /home/pc/.testenv/build/scipy
Storing debug log for failure in /home/pc/.pip/pip.log

```

How can I fix this?

**Comment by JohannesBuchner** [comment]
Did you try googling the error? "no lapack/blas resources found"
It is probably easiest to install numpy, scipy, lapack, blas Ubuntu packages.

**Comment by iclearn** [comment]
Try installing using conda, if you have installed python using conda,
     `conda install -c scitools imagehash`

**Comment by sslavian812** [comment]
As for me, the solution was to upgrade the pip:
`pip install --upgrade pip`
