### ISSUE TITLE
Cannot install on Centos w/ python 3.6

### ISSUE THREAD

**Issue by alexeyda** [JohannesBuchner/imagehash#63]
```
bash-4.2# /usr/bin/pip3.6 install imagehash --no-cache-dir
Collecting imagehash
  Downloading ImageHash-3.5.tar.gz (294kB)
    100% |################################| 296kB 298kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7g_5kb6z/imagehash/setup.py", line 10, in <module>
        long_description = f.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 261: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7g_5kb6z/imagehash/
```

**Comment by JohannesBuchner** [comment]
Aha, saw this issue only after replying to your email. Thanks for the report. Version 3.7, commit  43481e5  should fix this. Could you please try again.

**Comment by alexeyda** [comment]
Works now. Thank you
