### ISSUE TITLE
scipy error: dtype uint8 not supported

### ISSUE THREAD

**Issue by kineticac** [JohannesBuchner/imagehash#65]
With the latest code, using phash results in this error:

```
$ ./find_similar_images.py phash .
Traceback (most recent call last):
  File "./find_similar_images.py", line 61, in <module>
    find_similar_images(userpath=userpath, hashfunc=hashfunc)
  File "./find_similar_images.py", line 21, in find_similar_images
    hash = hashfunc(Image.open(img))
  File "/code/imagehash/imagehash/__init__.py", line 157, in phash
    dct = scipy.fftpack.dct(scipy.fftpack.dct(pixels, axis=0), axis=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/fftpack/realtransforms.py", line 124, in dct
    return _dct(x, type, n, axis, normalize=norm, overwrite_x=overwrite_x)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/fftpack/realtransforms.py", line 223, in _dct
    raise ValueError("dtype %s not supported" % tmp.dtype)
ValueError: dtype uint8 not supported
```

**Comment by JohannesBuchner** [comment]
Thanks for reporting this. Could you attach the problematic image?

**Comment by JohannesBuchner** [comment]
This seems related: https://stackoverflow.com/questions/12307429/scipy-fftpack-and-float64

**Comment by kineticac** [comment]
Here is the image:
https://www.dropbox.com/s/xp7qnsnkw3h0bpv/test.jpg?dl=0

I'm not sure how the link is related though. Double precision problem with endians?

**Comment by yan-wei** [comment]
I meet the same problem, any solutions?  Here is the image: http://a.abcnews.com/images/Entertainment/fast-eddie-clarke-gty-jef-180111_4x3t_384.jpg

**Comment by JohannesBuchner** [comment]
I can not reproduce this with either images. I have scipy 0.16.1, pillow 3.4.2-r1 and imagehash 4.0.

I run
```
from PIL import Image
import imagehash
import sys
img = Image.open(sys.argv[1])
hash = imagehash.phash(img)
print('phash:', hash)
```
but do not get any exception.

**Comment by yan-wei** [comment]
@JohannesBuchner  I upgrade my scipy to the latest version, and it solves my problem. Thanks. 
I used to use scipy 0.13. Now I use scipy 1.0.0.

**Comment by juq7ang** [comment]
```
Traceback (most recent call last):
  File "/Users/ju/Desktop/Logo-AI/debug.py", line 22, in <module>
    hash1 = imagehash.phash(Image.open('template/1.jpg'),hash_size=hash_size,highfreq_factor=highfreq_factor)
  File "/Library/Python/2.7/site-packages/imagehash/__init__.py", line 166, in phash
    dct = scipy.fftpack.dct(scipy.fftpack.dct(pixels, axis=0), axis=1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/fftpack/realtransforms.py", line 124, in dct
    return _dct(x, type, n, axis, normalize=norm, overwrite_x=overwrite_x)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/scipy/fftpack/realtransforms.py", line 223, in _dct
    raise ValueError("dtype %s not supported" % tmp.dtype)
ValueError: dtype uint8 not supported
```
The same problem with me, but I write a function to do it.
I can't raise any other problem, I use openCV to do.

```
import cv2
import numpy as np
from compiler.ast import flatten

def calculate_pHash(img1, img2):
    """
        缩小图片：32 * 32是一个较好的大小，这样方便DCT计算
        转化为灰度图：把缩放后的图片转化为256阶的灰度图。（具体算法见平均哈希算法步骤）
        计算DCT:DCT把图片分离成分率的集合
        缩小DCT：DCT计算后的矩阵是32 * 32，保留左上角的8 * 8，这些代表的图片的最低频率
        计算平均值：计算缩小DCT后的所有像素点的平均值。
        进一步减小DCT：大于平均值记录为1，反之记录为0.
        得到信息指纹：组合64个信息位，顺序随意保持一致性。
    :param img: 图片
    :return: hash值
    """
    image1 = cv2.resize(img1,(32,32))
    image2 = cv2.resize(img2,(32,32))
    gray1 = cv2.cvtColor(image1,cv2.COLOR_BGR2GRAY)
    gray2 = cv2.cvtColor(image2,cv2.COLOR_BGR2GRAY)
    # 将灰度图转为浮点型，再进行dct变换
    dct1 = cv2.dct(np.float32(gray1))
    dct2 = cv2.dct(np.float32(gray2))
    # 取左上角的8*8，这些代表图片的最低频率
    # 在python中进行掩码操作，可以直接这样取出图像矩阵的某一部分
    dct1_roi = dct1[0:8,0:8]
    dct2_roi = dct2[0:8,0:8]
    hash1 = get_hash(dct1_roi)
    hash2 = get_hash(dct2_roi)
    return Hamming_distance(hash1,hash2)
```

**Comment by JohannesBuchner** [comment]
Hi @juq7ang, please update your scipy.
