### ISSUE TITLE
can not import imagehash

### ISSUE THREAD

**Issue by qifengzhou** [JohannesBuchner/imagehash#86]
Hi, 

I installed imagehash via Anaconda in a conda environment, but it can not be imported in Spyder. 
The error shows:
```
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
Type "copyright", "credits" or "license" for more information.

IPython 6.4.0 -- An enhanced Interactive Python.
runfile('/home/qifeng/.config/spyder-py3/temp.py', wdir='/home/qifeng/.config/spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-1-3e5372b045d4>", line 1, in <module>
    runfile('/home/qifeng/.config/spyder-py3/temp.py', wdir='/home/qifeng/.config/spyder-py3')

  File "/home/qifeng/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/qifeng/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/qifeng/.config/spyder-py3/temp.py", line 7, in <module>
    from imagehash import phash

ModuleNotFoundError: No module named 'imagehash'"
```
My system specs are:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

The conda environment which imagehash installed is:
packages in environment at /home/qifeng/anaconda3/envs/whale:

Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py27_1000    conda-forge
freetype                  2.9.1                h8a8886c_1  
imagehash                 4.0                        py_0    conda-forge
intel-openmp              2019.1                      144  
jpeg                      9b                   h024ee3a_2  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.36               hbc83047_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
mkl                       2019.1                      144  
ncurses                   6.1                  he6710b0_1  
numpy                     1.11.3           py27h3dfced4_4  
olefile                   0.42.1                   py27_1    scitools/label/archive
openssl                   1.1.1a            h14c3975_1000    conda-forge
pillow                    5.4.1            py27h34e0f95_0  
pip                       19.0.1                   py27_0  
python                    2.7.15               h9bab390_6  
pywavelets                0.4.0               np111py27_0    scitools/label/archive
readline                  7.0                  h7b6447c_5  
scipy                     1.2.0            py27h7c811a0_0  
setuptools                40.7.3                   py27_0  
six                       1.12.0                   pypi_0    pypi
sqlite                    3.26.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.32.3                   py27_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 

spyder version is spyder/bionic,bionic 3.2.6+dfsg1-2 all

Could you please help?

**Comment by qifengzhou** [comment]
The problem was I used spyder from the general setting, but installing spyder in this conda environment, I could import the packages. 

This is not an imagehash problem, I will close the issue but leave this here for someone who might have the same problem.
